DefaultContentLanguage = "pt-br"
title = "Tableless"
baseURL = "https://tableless.com.br/"
theme = "tableless"
SectionPagesMenu = "main"
metaDataFormat="json"
canonifyURLs = true

disqusShortname = "tableless"
googleAnalytics = "UA-335027-1"

enableRobotsTXT = true

[params]
    siteName = "Tableless"
    description = "Website com artigos e textos sobre Padrões Web, Design, Back-end e Front-end tudo em um só lugar. "

[permalinks]
    posts = "/:filename"
    pages = "/:filename"

[taxonomies]
    tag = "tags"
    category = "categories"
    author = "author"
