backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Authors", name: "authors", widget: "list"}
      - {label: "Date", name: "date", widget: "date", format: "2017-09-17"}
      - {label: "Image", name: "image", widget: "string"}
      - {label: "Categories", name: "categories", widget: "list", default: ["front-end, back-end, design, wordpress, eventos-e-workshops, cotidiano, tecnologia, noticias, carreira, freebies, podcasts"]}
      - {label: "Tags", name: "tags", widget: "list", default: ["html, css, javascript, reactjs, nodejs, php, java, angular, sass, less, css3, jquery, ux, ui"]}
      - {label: "Body", name: "body", widget: "markdown"}